### PR TITLE
Use resource-backed-dask-array, copy dask chunks by default

### PR DESCRIPTION
**Pull request by tlambert03**
pull out that module into it's own repo https://github.com/tlambert03/resource-backed-dask-array

This also _always_ uses `array.copy()` in the _dask chunk function.  It's conceivable may slow down certain read operations, but there were still some lingering segfaults that I can't figure out.  (added a test for one).  Better safe than sorry for now.  We can revisit performance in the future (or, users can play with `to_dask(copy=False)`)

### CODE REVIEW

**Comment by tlambert03** [comment]
hey, @jacksonmaxfield

Small heads up here.  In addition to pulling out that resource-backed array thingy, this PR is largely for improved compatibility with aicsimagio.  After a long time playing with it, I can't quite figure out what about that `np.test_array_equal` bit to causing a segfault, so I'm falling back to the safer behavior of using `np.copy` on dask chunks by default.  This definitely fixes that segfault, but may decrease dask performance a bit.  Better safe than sorry, and users can still futz with `copy=False` if they want.

will release and make PR to aicsimageio

**Comment by tlambert03** [comment]
oh, note also that I'm adding a direct aicsimageio test here as well, so we should be safe to pin `>=` from now on, as this will fail if it fails the aics test

**Comment by tlambert03** [comment]
actually @VolkerH as well, I hope that this will eliminate the remaining segfaults you were seeing (at the cost of a little performance, but there's a `copy` param you can turn off if you want to be daring ;))

**Comment by VolkerH** [comment]
Thanks for tagging me @tlambert03, I hope to give this a try soon.

**Comment by VolkerH** [comment]
Hi @tlambert03,

sorry for the late feedback. I just upgraded to the latest packaged version (0.2.1) and the one of my tests that resulted in a segmentation fault with 0.1.6 now passes:

```
def _load_nd2(filepath):
    with ND2File(filepath) as f:
        return f.to_dask()


@pytest.mark.skipif(RUNNING_IN_CI, reason="Test resource missing")
def test_nd2_from_context_mgr():
    arr = _load_nd2(dataset_nd2)
    np_slice = np.array(arr[0, 0, :, :])
```
Thanks for fixing this !

**Comment by tlambert03** [comment]
thanks for the update!

**Pull request merged**
