### PR TITLE
feat: add `write_tiff` export to OME-TIFF, include full metadata as StructuredAnnotation

### LINKED ISSUE #215: feat: export to OME-TIFF, include full metadata as StructuredAnnotation
This is tracking a feature request from @phisanti (that I also think is a good idea) for exporting as much metadata as we can gather in the `ome_types.OME` object that we export from `ND2File.ome_metadata()`.

However, while https://github.com/tlambert03/ome-types/pull/249 does make this a bit easier... we still have issues because:
1. [MapAnnotation/Value](https://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome_xsd.html#MapAnnotation_Value) children must all be [`M`](https://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome_xsd.html#Map_M) and the value of M must be a plain string... this means that nested dicts are not allowed.
2. related to the first point, we can only pass strings or other things that can be cast to strings (like integers) as a value.  So all of the array values in the unstructured metadata are also not allowed.

So, I think we either have to just dump it all into a single json string, or do a ton of value checking and either exclude or selectively cat to json the stuff that the OME model doesn't take naturally.

### PR DESCRIPTION
**Pull request by tlambert03**
closes #215 and adds an export to ome-tiff

```python
import nd2

with nd2.ND2File('your.nd2') as f:
    f.write_tiff('output.ome.tif')
```

### CODE REVIEW

**Comment by tlambert03** [comment]
@phisanti, not sure if you get these github pings.  But this is at a state where you might want to try it out:

```
pip install git+https://github.com/tlambert03/nd2.git@update-ome
```

then
```python
import nd2

with nd2.ND2File('your.nd2') as f:
    f.write_tiff('output.ome.tif')
```

**Comment by tlambert03** [comment]
ah: one feature i still need to implement is exporting multi-position ND acquisitions to multi-series tiff

**Comment by tlambert03** [comment]
@cgohlke, if I could borrow a moment of your time, i would greatly appreciate your feedback on the `nd2_to_tiff` implementation in `tiff.py` in the PR.  Mostly curious to know whether I've missed any performance or metadata considerations, and whether I've used the tifffile API as optimally as I could.   I would also like to know if you have tips on what I would need to change to implement multi-series files, for nd2 files that have multiple stage positions (i believe 6D is the highest nd2 will ever go though)

**Comment by cgohlke** [comment]
The use of the iterator looks correct to me as long as it returns frames of same shape and dtype. 

To write a second series, call `tif.write(...)` again.

`Christoph suggests encode("ascii")`: Did I? TIFF strings must be ASCII 7-bit, which is enforced by tifffile. In order to write OME-XML, encode it as UTF8. Encoded bytes are not checked by tifffile.

**Comment by tlambert03** [comment]
>The use of the iterator looks correct to me as long as it returns frames of same shape and dtype.
>To write a second series, call tif.write(...) again.

thanks!

> Did I? TIFF strings must be ASCII 7-bit, which is enforced by tifffile. In order to write OME-XML, encode it as UTF8. Encoded bytes are not checked by tifffile.

oops, I'm sorry that indeed wasn't you!  that was someone else on imagesc (sorry, got mixed up in all the various posts I was searching).  Ok great, then it sounds like I shouldn't do anything special on the ome_types side to make sure the output is ascii-encodable?

**Pull request merged**
