### PR TITLE
Make 'periodDiff' optional in TimeLoopParams construction

### PR DESCRIPTION
**Pull request by SeanLeRoy**
[See discussion here](https://github.com/AllenCellModeling/aicsimageio/issues/488).

This is intended to allow `periodDiff` be an optional parameter to `TimeLoopParams`

### CODE REVIEW

**Comment by tlambert03** [comment]
works for me if it works for you!  I can follow up in another PR with a more general catch-all fix for missing params

**Review by tlambert03 — APPROVED** [review]

**Comment by tlambert03** [comment]
@SeanLeRoy, you have it marked as draft, so let me know if you want to do more.  Otherwise , lgtm

**Comment by SeanLeRoy** [comment]
Ah it was just a draft until I got your approval during our discussion, hopefully you saw the 2 failing checks. I am assuming so and that they are irrelevant (it seems so) and will merge this end of day unless told otherwise!

**Comment by tlambert03** [comment]
Yeah the fails are unrelated and fixed in another PR in the meantime

**Comment by SeanLeRoy** [comment]
@tlambert03 I don't have write access to your `main` branch so I can't merge this it seems, feel free to merge whenever/if you see fit.

**Comment by SeanLeRoy** [comment]
@tlambert03 I don't have write access to your repo/`main` branch so I can't merge this. Feel free to whenever/if you see fit

**Comment by tlambert03** [comment]
Yep different org :) thanks!

**Pull request merged**
